import globals from 'globals';
import pluginGoogleAppsScript from 'eslint-plugin-googleappsscript';
import prettierConfig from 'eslint-config-prettier';

export default [
  // Google Apps Script server-side files (both src and dev/backend)
  {
    files: ['src/**/*.js', 'dev/backend/**/*.js'],
    plugins: {
      googleappsscript: pluginGoogleAppsScript,
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...globals.es2020,
        ...pluginGoogleAppsScript.environments.googleappsscript.globals,

        // =================================================================
        // Project specific globals - 型定義で対応できないもののみ
        // =================================================================
        ACCOUNTING_MASTER_SHEET_NAME: 'readonly',
        ADMIN_EMAIL: 'readonly',
        // BANK_*: TypeScript定義に委譲 (window.BANK)
        // BANK_ACCOUNT: 'readonly',
        // BANK_BRANCH: 'readonly',
        // BANK_COTRA_PHONE: 'readonly',
        // BANK_NAME: 'readonly',
        BackendErrorHandler: 'readonly',
        CACHE_EXPIRY_SECONDS: 'readonly',
        CACHE_KEYS: 'readonly',
        CALENDAR_IDS: 'readonly',
        CALENDAR_IDS_RAW: 'readonly',
        CLASSROOM_CAPACITIES: 'readonly',
        CLASSROOM_SHEET_NAMES: 'readonly',
        CLASSROOM_TYPE_SESSION_BASED: 'readonly',
        CLASSROOM_TYPE_TIME_DUAL: 'readonly',
        CLASSROOM_TYPE_TIME_FULL: 'readonly',
        COLOR_HEADER_BACKGROUND: 'readonly',
        COLOR_LIGHT_BLUE: 'readonly',
        COLOR_LIGHT_GREEN: 'readonly',
        COLOR_LIGHT_ORANGE: 'readonly',
        COLOR_LIGHT_RED: 'readonly',
        COLUMN_WIDTH_BEGINNER_START: 'readonly',
        COLUMN_WIDTH_CAPACITY: 'readonly',
        COLUMN_WIDTH_CLASSROOM: 'readonly',
        COLUMN_WIDTH_CLASSROOM_TYPE: 'readonly',
        COLUMN_WIDTH_DATE: 'readonly',
        COLUMN_WIDTH_NOTES: 'readonly',
        COLUMN_WIDTH_STATUS: 'readonly',
        COLUMN_WIDTH_TIME: 'readonly',
        COLUMN_WIDTH_VENUE: 'readonly',
        CONSTANTS: 'readonly', // Must be enabled for dev/backend/
        DATA_START_ROW: 'readonly',
        DISCOUNT_OPTION_30MIN: 'readonly',
        DISCOUNT_OPTION_60MIN: 'readonly',
        DISCOUNT_OPTION_NONE: 'readonly',
        FrontendErrorHandlerTemplate: 'readonly',
        HEADER_ACCOUNTING_DETAILS: 'readonly',
        HEADER_ARCHIVE_PREFIX: 'readonly',
        HEADER_BREAK_END: 'readonly',
        HEADER_BREAK_START: 'readonly',
        HEADER_CHISEL_RENTAL: 'readonly',
        HEADER_CLASSROOM: 'readonly',
        HEADER_CLASS_COUNT: 'readonly',
        HEADER_CLASS_END: 'readonly',
        HEADER_CLASS_START: 'readonly',
        HEADER_CO: 'readonly',
        HEADER_DATE: 'readonly',
        HEADER_END_TIME: 'readonly',
        HEADER_FIRST_LECTURE: 'readonly',
        HEADER_FROM: 'readonly',
        HEADER_IN_THE_FUTURE: 'readonly',
        HEADER_LINE: 'readonly',
        HEADER_MESSAGE_TO_TEACHER: 'readonly',
        HEADER_NAME: 'readonly',
        HEADER_NICKNAME: 'readonly',
        HEADER_NOTES: 'readonly',
        HEADER_ORDER: 'readonly',
        HEADER_PARTICIPANT_COUNT: 'readonly',
        HEADER_PHONE: 'readonly',
        HEADER_PICKUP: 'readonly',
        HEADER_REAL_NAME: 'readonly',
        HEADER_RESERVATION_ID: 'readonly',
        HEADER_ROW: 'readonly',
        HEADER_SCHEDULE_BEGINNER_CAPACITY: 'readonly',
        HEADER_SCHEDULE_BEGINNER_START: 'readonly',
        HEADER_SCHEDULE_CLASSROOM: 'readonly',
        HEADER_SCHEDULE_DATE: 'readonly',
        HEADER_SCHEDULE_FIRST_END: 'readonly',
        HEADER_SCHEDULE_FIRST_START: 'readonly',
        HEADER_SCHEDULE_NOTES: 'readonly',
        HEADER_SCHEDULE_SECOND_END: 'readonly',
        HEADER_SCHEDULE_SECOND_START: 'readonly',
        HEADER_SCHEDULE_STATUS: 'readonly',
        HEADER_SCHEDULE_TOTAL_CAPACITY: 'readonly',
        HEADER_SCHEDULE_TYPE: 'readonly',
        HEADER_SCHEDULE_VENUE: 'readonly',
        HEADER_START_TIME: 'readonly',
        HEADER_STATUS: 'readonly',
        HEADER_STUDENT_ID: 'readonly',
        HEADER_TIME: 'readonly',
        HEADER_TRANSPORTATION: 'readonly',
        HEADER_UNIFIED_CLASS_COUNT: 'readonly',
        HEADER_VENUE: 'readonly',
        HEADER_WORK_IN_PROGRESS: 'readonly',
        INTRO_LECTURE_CAPACITY: 'readonly',
        ITEM_NAME_CHISEL_RENTAL: 'readonly',
        ITEM_NAME_DISCOUNT: 'readonly',
        ITEM_NAME_FIRST_LECTURE: 'readonly',
        ITEM_NAME_MAIN_LECTURE: 'readonly',
        ITEM_TYPE_MATERIAL: 'readonly',
        ITEM_TYPE_SALES: 'readonly',
        ITEM_TYPE_TUITION: 'readonly',
        LOCK_WAIT_TIME_MS: 'readonly',
        LOG_ACTION_RESERVATION_CANCEL: 'readonly',
        LOG_ACTION_RESERVATION_EDIT: 'readonly',
        LOG_ACTION_ROSTER_EDIT: 'readonly',
        LOG_ACTION_ROW_INSERT: 'readonly',
        LOG_SHEET_NAME: 'readonly',
        MATERIAL_INFO_PREFIX: 'readonly',
        // MSG_*: Used in dev/backend/
        MSG_CANCEL: 'readonly',
        MSG_ERROR: 'readonly',
        MSG_EXISTING_SHEET_WARNING: 'readonly',
        MSG_PROCESSING_INTERRUPTED: 'readonly',
        MSG_SHEET_INITIALIZATION: 'readonly',
        MSG_SUCCESS: 'readonly',
        NUMAZU_CLASSROOM_NAME: 'readonly',
        // PAYMENT_*: TypeScript定義に委譲 (window.PAYMENT)
        // PAYMENT_BANK_TRANSFER: 'readonly',
        // PAYMENT_CASH: 'readonly',
        // PAYMENT_COTRA: 'readonly',
        RESERVATION_DATA_START_ROW: 'readonly',
        ROSTER_SHEET_NAME: 'readonly',
        SALES_SPREADSHEET_ID: 'readonly',
        SCHEDULE_MASTER_HEADERS: 'readonly',
        // SCHEDULE_STATUS_*: Used in dev/backend/
        SCHEDULE_STATUS_CANCELLED: 'readonly',
        SCHEDULE_STATUS_COMPLETED: 'readonly',
        SCHEDULE_STATUS_SCHEDULED: 'readonly',
        SESSION_AFTERNOON: 'readonly',
        SESSION_ALL_DAY: 'readonly',
        SESSION_MORNING: 'readonly',
        SPECIAL_NO_PHONE_LOGIN_COMMAND_VALUE: 'readonly',
        SS_MANAGER: 'readonly',
        global: 'readonly',
        // STATUS_*: Used in dev/backend/
        STATUS_CANCEL: 'readonly',
        STATUS_WAITING: 'readonly',
        SpreadsheetManager: 'readonly',
        TIME_END_BUFFER_HOURS: 'readonly',
        TIME_STEP_MINUTES: 'readonly',
        TOKYO_CLASSROOM_NAME: 'readonly',
        TSUKUBA_CLASSROOM_NAME: 'readonly',
        TSUKUBA_MORNING_SESSION_END_HOUR: 'readonly',
        // UI_*: TypeScript定義に委譲 (window.UI)
        // UI_HISTORY_INITIAL_RECORDS: 'readonly',
        // UI_HISTORY_LOAD_MORE_RECORDS: 'readonly',
        // UI_LOADING_MESSAGE_INTERVAL: 'readonly',
        UNIT_30_MIN: 'readonly',
        UNIT_CM3: 'readonly',
        WEEKEND_SATURDAY: 'readonly',
        WEEKEND_SUNDAY: 'readonly',
        _logSalesForSingleReservation: 'readonly',
        _normalizeAndValidatePhone: 'readonly',
        _validateTimeBasedReservation: 'readonly',
        addAdminMenu: 'readonly',
        addCacheMenu: 'readonly',
        addCalendarEventsToSheetWithSpecifics: 'readonly',
        authenticateUser: 'readonly',
        cancelReservation: 'readonly',
        cancelReservationAndGetLatestData: 'readonly',
        createApiErrorResponse: 'readonly',
        createApiResponse: 'readonly',
        createHeaderMap: 'readonly',
        createIntegratedSheet: 'readonly',
        createSalesRow: 'readonly',
        createSampleScheduleData: 'readonly',
        createScheduleMasterSheet: 'readonly',
        debugTestSetup: 'readonly',
        doGet: 'readonly',
        doGetPerformanceTest: 'readonly',
        doGetTest: 'readonly',
        executeOperationAndGetLatestData: 'readonly',
        extractPersonalDataFromCache: 'readonly',
        extractUniqueDateClassroomCombinations: 'readonly',
        filterSchedulesByDateRange: 'readonly',
        findRowIndexByValue: 'readonly',
        generateScheduleDataWithDefaults: 'readonly',
        generateScheduleMasterFromExistingReservations: 'readonly',
        generateScheduleMasterFromExistingReservationsWithUI: 'readonly',
        getActiveSpreadsheet: 'readonly',
        getAllCacheInfo: 'readonly',
        getAllScheduledDates: 'readonly',
        getAppInitialData: 'readonly',
        getAvailableSlots: 'readonly',
        getAvailableSlotsForClassroom: 'readonly',
        getBatchData: 'readonly',
        getCacheInfo: 'readonly',
        getCacheVersions: 'readonly',
        getCachedData: 'readonly',
        getClassroomDefaults: 'readonly',
        getDataCount: 'readonly',
        getLoginData: 'readonly',
        getSheetByName: 'readonly',
        getSheetData: 'readonly',
        getSheetDataWithSearch: 'readonly',
        getUserReservations: 'readonly',
        getUsersWithoutPhoneNumber: 'readonly',
        handleEdit: 'readonly',
        handleError: 'readonly',
        handleOnChange: 'readonly',
        handleServerError: 'readonly',
        include: 'readonly',
        isReservationSheet: 'readonly',
        logActivity: 'readonly',
        makeReservation: 'readonly',
        makeReservationAndGetLatestData: 'readonly',
        migrateDataToIntegratedSheet: 'readonly',
        onOpen: 'readonly',
        prepareScheduleMasterSheet: 'readonly',
        rebuildAccountingMasterCache: 'readonly',
        rebuildAllCachesEntryPoint: 'readonly',
        rebuildAllReservationsCache: 'readonly',
        rebuildAllStudentsBasicCache: 'readonly',
        rebuildScheduleMasterCache: 'readonly',
        registerNewUser: 'readonly',
        runDirectTest: 'readonly',
        runRegressionTest: 'readonly',
        saveAccountingDetails: 'readonly',
        searchUsersWithoutPhone: 'readonly',
        sendAdminNotification: 'readonly',
        setupConditionalFormattingForLogSheet: 'readonly',
        setupTestEnvironment: 'readonly',
        shouldProcessRowByDate: 'readonly',
        transformReservationArrayToObject: 'readonly',
        transformReservationArrayToObjectWithHeaders: 'readonly',
        triggerScheduledCacheRebuild: 'readonly',
        updateReservationDetails: 'readonly',
        updateReservationDetailsAndGetLatestData: 'readonly',
        updateReservationMemoAndGetLatestData: 'readonly',
        updateUserProfile: 'readonly',
        verifyMigratedData: 'readonly',
        withTransaction: 'readonly',
        writeScheduleDataToSheet: 'readonly',
        convertReservationsToObjects: 'readonly',
        getHeaderIndex: 'readonly',
        getCachedStudentById: 'readonly',
        getCachedReservationsFor: 'readonly',
        diagnoseAndFixScheduleMasterCache: 'readonly',
      },
    },
    rules: {
      'no-undef': 'warn',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', vars: 'local' }],
      'no-console': 'off',
      'no-var': 'warn',
      'prefer-const': 'warn',
      'no-multiple-empty-lines': ['warn', { max: 2 }],
      'no-trailing-spaces': 'warn',
    },
  },
  // Node.js tools
  {
    files: ['tools/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module', // Changed from commonjs
      globals: {
        ...globals.node,
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': 'off',
      'no-var': 'warn',
      'prefer-const': 'warn',
    },
  },
  // Special config for frontend test file
  {
    files: ['tools/frontend-test.js'],
    languageOptions: {
      globals: {
        ...globals.browser,
        escapeHTML: 'readonly',
        setState: 'readonly',
      },
    },
  },
  // Root-level test files
  {
    files: ['test-*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...globals.es2020,
        CONSTANTS: 'readonly',
        C: 'readonly',
        STATUS: 'readonly',
        UI: 'readonly',
        MESSAGES: 'readonly',
        BANK: 'readonly',
        PAYMENT: 'readonly',
        HEADERS: 'readonly',
      },
    },
    rules: {
      'no-undef': 'warn',
      'no-unused-vars': 'off',
      'no-console': 'off',
    },
  },
  // Ignore patterns
  {
    ignores: [
      'node_modules/**',
      'archive/**',
      'docs/**',
      'test/**',
      '.claude/**',
      '.vscode/**',
      '.github/**',
      'src/**/*.html', // Skip HTML files as they need special parsing
      'eslint.config.js', // Skip our own config file
    ],
  },
  prettierConfig,
];
