import globals from 'globals';
import pluginGoogleAppsScript from 'eslint-plugin-googleappsscript';

export default [
  // Google Apps Script server-side files
  {
    files: ['src/**/*.js'],
    plugins: {
      googleappsscript: pluginGoogleAppsScript,
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...globals.es2020,
        ...pluginGoogleAppsScript.environments.googleappsscript.globals,

        // =================================================================
        // Project specific globals and functions from all files
        // =================================================================
        global: 'writable',
        cache: 'readonly',
        ARCHIVE_SHEET_NAMES: 'readonly',

        // Functions from various files
        SS_MANAGER: 'readonly',
        getActiveSpreadsheet: 'readonly',
        getSpreadsheetTimezone: 'readonly',
        getCachedData: 'readonly',
        setCachedData: 'readonly',
        createApiResponse: 'readonly',
        BackendErrorHandler: 'readonly',
        transformReservationArrayToObject: 'readonly',
        transformReservationArrayToObjectWithHeaders: 'readonly',
        getUserHistoryFromCache: 'readonly',
        include: 'readonly',
        doGet: 'readonly',
        onOpen: 'readonly',
        addAdminMenu: 'readonly',
        addCacheMenu: 'readonly',
        handleOnChange: 'readonly',
        handleEdit: 'readonly',
        doGetTest: 'readonly',
        debugTestSetup: 'readonly',
        runDirectTest: 'readonly',
        doGetPerformanceTest: 'readonly',
        runRegressionTest: 'readonly',
        setupTriggers: 'readonly',
        dailyBatchTrigger: 'readonly',
        processChange: 'readonly',
        processCellEdit: 'readonly',
        handleError: 'readonly',
        rebuildAllCachesEntryPoint: 'readonly',
        setCheckboxChoices: 'readonly',
        createScheduleMasterSheet: 'readonly',
        generateScheduleMasterFromExistingReservationsWithUI: 'readonly',
        setupTestEnvironment: 'readonly',
        createIntegratedSheet: 'readonly',
        migrateDataToIntegratedSheet: 'readonly',
        verifyMigratedData: 'readonly',
        manuallyReSortAndNumberSheet: 'readonly',
        manuallyFormatActiveSheet: 'readonly',
        addCalendarEventsToSheetWithSpecifics: 'readonly',
        processYesterdayData: 'readonly',
        processTodayData: 'readonly',
        processOldestDate: 'readonly',
        cleanupPropertiesServiceCache: 'readonly',
        checkCacheCapacity: 'readonly',
        cleanupOldCaches: 'readonly',
        updateRosterCache: 'readonly',
        testSpreadsheetManagerFunction: 'readonly',
        testAvailableSlotsFunction: 'readonly',
        performanceComparisonFunction: 'readonly',
        testBasicFunctionality: 'readonly',
        testRegressionSuite: 'readonly',
        testErrorHandling: 'readonly',
        logActivity: 'readonly',
        createHeaderMap: 'readonly',
        shouldProcessRowByDate: 'readonly',
        formatSheetWithBordersSafely: 'readonly',
        _rebuildFutureBookingsCacheForStudent: 'readonly',
        getSheetByName: 'readonly',
        handleRowInsert: 'readonly',
        sortAndRenumberDateBlock: 'readonly',
        triggerSummaryUpdateFromEdit: 'readonly',
        updateBillableTime: 'readonly',
        updateGanttChart: 'readonly',
        updateAndSortSheet: 'readonly',
        updateFutureReservations: 'readonly',
        getRosterData: 'readonly',
        populateReservationWithRosterData: 'readonly',
        handleReservationNameClear: 'readonly',
        insertEmptyRowForCancellation: 'readonly',
        getAccountingMasterData: 'readonly',
        findRowIndexByValue: 'readonly',
        getAllScheduledDates: 'readonly',
        sendAdminNotification: 'readonly',
        getScheduleDataFromSheet: 'readonly',
        rebuildAllStudentsBasicCache: 'readonly',
        getAppInitialData: 'readonly',
        getUserReservations: 'readonly',
        getAvailableSlots: 'readonly',
        rebuildAllReservationsCache: 'readonly',
        _updateFutureBookingsCacheIncrementally: 'readonly',
        getParticipationHistory: 'readonly',
        createSalesRow: 'readonly',
        drawBorders: 'readonly',
        makeReservation: 'readonly',
        cancelReservation: 'readonly',
        updateReservationDetails: 'readonly',
        getUsersWithoutPhoneNumber: 'readonly',
        updateMemoAndGetLatestHistory: 'readonly',
        withTransaction: 'readonly',
        getSheetData: 'readonly',
        getSheetDataWithSearch: 'readonly',

        // Constants from 00_Constants.js
        CONSTANTS: 'readonly',
        TOKYO_CLASSROOM_NAME: 'readonly',
        NUMAZU_CLASSROOM_NAME: 'readonly',
        TSUKUBA_CLASSROOM_NAME: 'readonly',
        CLASSROOM_SHEET_NAMES: 'readonly',
        CLASSROOM_CAPACITIES: 'readonly',
        INTRO_LECTURE_CAPACITY: 'readonly',
        TSUKUBA_MORNING_SESSION_END_HOUR: 'readonly',
        LOCK_WAIT_TIME_MS: 'readonly',
        ROSTER_SHEET_NAME: 'readonly',
        ACCOUNTING_MASTER_SHEET_NAME: 'readonly',
        LOG_SHEET_NAME: 'readonly',
        HEADER_STUDENT_ID: 'readonly',
        HEADER_RESERVATION_ID: 'readonly',
        HEADER_DATE: 'readonly',
        HEADER_VENUE: 'readonly',
        HEADER_FIRST_LECTURE: 'readonly',
        HEADER_CHISEL_RENTAL: 'readonly',
        HEADER_START_TIME: 'readonly',
        HEADER_END_TIME: 'readonly',
        HEADER_CLASS_START: 'readonly',
        HEADER_CLASS_END: 'readonly',
        HEADER_BREAK_START: 'readonly',
        HEADER_BREAK_END: 'readonly',
        HEADER_CLASSROOM: 'readonly',
        HEADER_STATUS: 'readonly',
        HEADER_REAL_NAME: 'readonly',
        HEADER_NICKNAME: 'readonly',
        HEADER_PHONE: 'readonly',
        HEADER_CO: 'readonly',
        HEADER_PARTICIPANT_COUNT: 'readonly',
        HEADER_NAME: 'readonly',
        HEADER_CLASS_COUNT: 'readonly',
        HEADER_UNIFIED_CLASS_COUNT: 'readonly',
        HEADER_TIME: 'readonly',
        HEADER_WORK_IN_PROGRESS: 'readonly',
        HEADER_ORDER: 'readonly',
        HEADER_MESSAGE_TO_TEACHER: 'readonly',
        HEADER_ACCOUNTING_DETAILS: 'readonly',
        HEADER_LINE: 'readonly',
        HEADER_IN_THE_FUTURE: 'readonly',
        HEADER_NOTES: 'readonly',
        HEADER_FROM: 'readonly',
        HEADER_TRANSPORTATION: 'readonly',
        HEADER_PICKUP: 'readonly',
        ITEM_NAME_MAIN_LECTURE: 'readonly',
        ITEM_NAME_FIRST_LECTURE: 'readonly',
        ITEM_NAME_CHISEL_RENTAL: 'readonly',
        ITEM_NAME_DISCOUNT: 'readonly',
        STATUS_WAITING: 'readonly',
        STATUS_CANCEL: 'readonly',
        ITEM_TYPE_TUITION: 'readonly',
        ITEM_TYPE_SALES: 'readonly',
        ITEM_TYPE_MATERIAL: 'readonly',
        UNIT_30_MIN: 'readonly',
        UNIT_CM3: 'readonly',
        PAYMENT_CASH: 'readonly',
        SESSION_MORNING: 'readonly',
        SESSION_AFTERNOON: 'readonly',
        SESSION_ALL_DAY: 'readonly',
        PAYMENT_COTRA: 'readonly',
        PAYMENT_BANK_TRANSFER: 'readonly',
        BANK_COTRA_PHONE: 'readonly',
        BANK_NAME: 'readonly',
        BANK_BRANCH: 'readonly',
        BANK_ACCOUNT: 'readonly',
        DISCOUNT_OPTION_NONE: 'readonly',
        DISCOUNT_OPTION_30MIN: 'readonly',
        DISCOUNT_OPTION_60MIN: 'readonly',
        TIME_STEP_MINUTES: 'readonly',
        TIME_END_BUFFER_HOURS: 'readonly',
        UI_HISTORY_INITIAL_RECORDS: 'readonly',
        UI_HISTORY_LOAD_MORE_RECORDS: 'readonly',
        UI_LOADING_MESSAGE_INTERVAL: 'readonly',
        MSG_PROCESSING_INTERRUPTED: 'readonly',
        MSG_SHEET_INITIALIZATION: 'readonly',
        MSG_EXISTING_SHEET_WARNING: 'readonly',
        MSG_SUCCESS: 'readonly',
        MSG_ERROR: 'readonly',
        MSG_CANCEL: 'readonly',
        LOG_ACTION_ROSTER_EDIT: 'readonly',
        LOG_ACTION_RESERVATION_EDIT: 'readonly',
        LOG_ACTION_ROW_INSERT: 'readonly',
        LOG_ACTION_RESERVATION_CANCEL: 'readonly',
        COLOR_LIGHT_GREEN: 'readonly',
        COLOR_LIGHT_RED: 'readonly',
        COLOR_LIGHT_BLUE: 'readonly',
        COLOR_LIGHT_ORANGE: 'readonly',
        COLOR_HEADER_BACKGROUND: 'readonly',
        CLASSROOM_TYPE_SESSION_BASED: 'readonly',
        CLASSROOM_TYPE_TIME_DUAL: 'readonly',
        CLASSROOM_TYPE_TIME_FULL: 'readonly',
        SCHEDULE_STATUS_SCHEDULED: 'readonly',
        SCHEDULE_STATUS_CANCELLED: 'readonly',
        SCHEDULE_STATUS_COMPLETED: 'readonly',
        HEADER_SCHEDULE_DATE: 'readonly',
        HEADER_SCHEDULE_CLASSROOM: 'readonly',
        HEADER_SCHEDULE_VENUE: 'readonly',
        HEADER_SCHEDULE_TYPE: 'readonly',
        HEADER_SCHEDULE_FIRST_START: 'readonly',
        HEADER_SCHEDULE_FIRST_END: 'readonly',
        HEADER_SCHEDULE_SECOND_START: 'readonly',
        HEADER_SCHEDULE_SECOND_END: 'readonly',
        HEADER_SCHEDULE_BEGINNER_START: 'readonly',
        HEADER_SCHEDULE_TOTAL_CAPACITY: 'readonly',
        HEADER_SCHEDULE_BEGINNER_CAPACITY: 'readonly',
        HEADER_SCHEDULE_STATUS: 'readonly',
        HEADER_SCHEDULE_NOTES: 'readonly',
        MATERIAL_INFO_PREFIX: 'readonly',
        HEADER_ARCHIVE_PREFIX: 'readonly',
        DATA_START_ROW: 'readonly',
        SALES_SPREADSHEET_ID: 'readonly',
        CACHE_KEYS: 'readonly',

        // Constants from 01_Code.js
        RESERVATION_SPREADSHEET_ID: 'readonly',
        RESERVATION_DATA_START_ROW: 'readonly',
        SPECIAL_NO_PHONE_LOGIN_COMMAND_VALUE: 'readonly',
        ADMIN_EMAIL: 'readonly',
        SYNC_TARGET_HEADERS: 'readonly',
        COLUMN_WIDTH_DATE: 'readonly',
        COLUMN_WIDTH_CLASSROOM: 'readonly',
        COLUMN_WIDTH_VENUE: 'readonly',
        COLUMN_WIDTH_CLASSROOM_TYPE: 'readonly',
        COLUMN_WIDTH_TIME: 'readonly',
        COLUMN_WIDTH_BEGINNER_START: 'readonly',
        COLUMN_WIDTH_CAPACITY: 'readonly',
        COLUMN_WIDTH_STATUS: 'readonly',
        COLUMN_WIDTH_NOTES: 'readonly',
        CACHE_EXPIRY_SECONDS: 'readonly',
        SAMPLE_DATA_DAYS: 'readonly',
        WEEKEND_SUNDAY: 'readonly',
        WEEKEND_SATURDAY: 'readonly',
        HEADER_ROW: 'readonly',
        SALES_CATEGORY_TUITION: 'readonly',
        SALES_CATEGORY_SALES: 'readonly',
        CLASSROOM_TRANSFER_SETTINGS: 'readonly',
        GOOGLE_FORM_IDS_RAW: 'readonly',
        GOOGLE_FORM_IDS: 'readonly',
        FORM_QUESTION_TITLES: 'readonly',
        CALENDAR_IDS_RAW: 'readonly',
        CALENDAR_IDS: 'readonly',
        SCHEDULE_MASTER_HEADERS: 'readonly',
      },
    },
    rules: {
      'no-undef': 'warn',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', vars: 'local' }],
      'no-console': 'off',
      'no-var': 'warn',
      'prefer-const': 'warn',
      'no-multiple-empty-lines': ['warn', { max: 2 }],
      'no-trailing-spaces': 'warn',
    },
  },
  // Node.js tools
  {
    files: ['tools/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module', // Changed from commonjs
      globals: {
        ...globals.node,
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': 'off',
      'no-var': 'warn',
      'prefer-const': 'warn',
    },
  },
  // Special config for frontend test file
  {
    files: ['tools/frontend-test.js'],
    languageOptions: {
      globals: {
        ...globals.browser,
        escapeHTML: 'readonly',
        setState: 'readonly',
      },
    },
  },
  // Ignore patterns
  {
    ignores: [
      'node_modules/**',
      'archive/**',
      'docs/**',
      'test/**',
      '.claude/**',
      '.vscode/**',
      '.github/**',
      'src/**/*.html', // Skip HTML files as they need special parsing
      'eslint.config.js', // Skip our own config file
    ],
  },
];
