/**
 * @file Global type aliases bridging module exports to ambient names.
 * Generated to maintain backward compatibility with legacy JSDoc annotations.
 */

import type { AccountingCacheData as ____core_common_0 } from './core/common';
import type { AccountingCalculationResult as ____view_handlers_0 } from './view/handlers';
import type { AccountingDetails as ____core_common_1 } from './core/common';
import type { AccountingDetailsCore as ____core_accounting_0 } from './core/accounting';
import type { AccountingFormDto as ____view_state_0 } from './view/state';
import type { AccountingMasterItem as ____core_common_2 } from './core/common';
import type { AccountingMasterItemCore as ____core_accounting_1 } from './core/accounting';
import type { AccountingRowConfig as ____view_components_0 } from './view/components';
import type { ActionButtonSectionConfig as ____view_components_1 } from './view/components';
import type { ActionHandler as ____view_handlers_1 } from './view/handlers';
import type { ActionHandlerData as ____view_handlers_2 } from './view/handlers';
import type { ActionHandlers as ____view_handlers_3 } from './view/handlers';
import type { ActionType as ____view_state_1 } from './view/state';
import type { ApiErrorResponse as ____core_common_3 } from './core/common';
import type { ApiResponse as ____core_common_4 } from './core/common';
import type { ApiResponseData as ____core_common_5 } from './core/common';
import type { ApiResponseGeneric as ____core_common_6 } from './core/common';
import type { ApiSuccessResponse as ____core_common_7 } from './core/common';
import type { AppInitialData as ____core_common_8 } from './core/common';
import type { AppState as ____view_state_2 } from './view/state';
import type { AsyncEventHandler as ____view_handlers_4 } from './view/handlers';
import type { AsyncGenericCallback as ____view_handlers_5 } from './view/handlers';
import type { AsyncVoidCallback as ____view_handlers_6 } from './view/handlers';
import type { BadgeType as ____view_components_2 } from './view/components';
import type { BatchDataPayload as ____core_common_9 } from './core/common';
import type { BatchDataResponse as ____core_common_10 } from './core/common';
import type { BatchDataResult as ____core_common_11 } from './core/common';
import type { ButtonConfig as ____view_components_3 } from './view/components';
import type { ButtonStyles as ____view_design-system_0 } from './view/design-system';
import type { CacheDataStructure as ____core_common_12 } from './core/common';
import type { CacheInfo as ____core_common_13 } from './core/common';
import type { CardContainerConfig as ____view_components_4 } from './view/components';
import type { CardHistoryConfig as ____view_design-system_1 } from './view/design-system';
import type { CardStateConfig as ____view_design-system_2 } from './view/design-system';
import type { CardStates as ____view_design-system_3 } from './view/design-system';
import type { CardStyles as ____view_design-system_4 } from './view/design-system';
import type { ChangeEventHandler as ____view_handlers_7 } from './view/handlers';
import type { CheckboxConfig as ____view_components_5 } from './view/components';
import type { ChunkedCacheMetadata as ____core_common_14 } from './core/common';
import type { ClassifiedAccountingItemsCore as ____core_accounting_2 } from './core/accounting';
import type { ClassroomColorConfig as ____view_design-system_5 } from './view/design-system';
import type { ClassroomColors as ____view_design-system_6 } from './view/design-system';
import type { ClassroomName as ____view_handlers_8 } from './view/handlers';
import type { ClickEventHandler as ____view_handlers_9 } from './view/handlers';
import type { ComponentConfig as ____view_components_6 } from './view/components';
import type { ComponentFunction as ____view_components_7 } from './view/components';
import type { ComponentProps as ____view_components_8 } from './view/components';
import type { ComponentQuerySelector as ____view_dom_0 } from './view/dom';
import type { ComponentQuerySelectorAll as ____view_dom_1 } from './view/dom';
import type { ComponentRenderer as ____view_components_9 } from './view/components';
import type { ComponentSize as ____view_components_10 } from './view/components';
import type { ComponentStyle as ____view_components_11 } from './view/components';
import type { ComputedStateData as ____view_state_3 } from './view/state';
import type { ConfirmDialogConfig as ____view_components_12 } from './view/components';
import type { DOMElementSafeAccess as ____view_dom_2 } from './view/dom';
import type { DashboardSectionConfig as ____view_components_13 } from './view/components';
import type { DateString as ____view_handlers_10 } from './view/handlers';
import type { DesignColors as ____view_design-system_7 } from './view/design-system';
import type { DesignSystemConfig as ____view_design-system_8 } from './view/design-system';
import type { DocumentWithTypedElements as ____view_dom_3 } from './view/dom';
import type { ElementWithCommonProperties as ____view_dom_4 } from './view/dom';
import type { ErrorHandler as ____view_handlers_11 } from './view/handlers';
import type { ErrorInfo as ____core_common_15 } from './core/common';
import type { EventHandler as ____view_handlers_12 } from './view/handlers';
import type { EventHandlerFunction as ____view_handlers_13 } from './view/handlers';
import type { FormEventHandler as ____view_handlers_14 } from './view/handlers';
import type { FrontendErrorHandlerClass as ____view_handlers_15 } from './view/handlers';
import type { FrontendErrorInfo as ____view_handlers_16 } from './view/handlers';
import type { GenericCallback as ____view_handlers_17 } from './view/handlers';
import type { HTMLElementEventListeners as ____view_dom_5 } from './view/dom';
import type { HTMLElementWithId as ____view_dom_6 } from './view/dom';
import type { HTMLGeneratorFunction as ____view_components_14 } from './view/components';
import type { HTMLString as ____view_components_15 } from './view/components';
import type { HeaderMapType as ____core_common_16 } from './core/common';
import type { InputConfig as ____view_components_16 } from './view/components';
import type { InputEventHandler as ____view_handlers_18 } from './view/handlers';
import type { InputStyles as ____view_design-system_9 } from './view/design-system';
import type { LayoutStyles as ____view_design-system_10 } from './view/design-system';
import type { LessonCore as ____core_lesson_0 } from './core/lesson';
import type { ListCardConfig as ____view_components_17 } from './view/components';
import type { MaterialRowConfig as ____view_components_18 } from './view/components';
import type { MemoSectionConfig as ____view_components_19 } from './view/components';
import type { ModalConfig as ____view_components_20 } from './view/components';
import type { ModalDialogConfig as ____view_components_21 } from './view/components';
import type { NavigationContext as ____view_state_4 } from './view/state';
import type { OtherSalesRowConfig as ____view_components_22 } from './view/components';
import type { PageContainerConfig as ____view_components_23 } from './view/components';
import type { PhoneNormalizationResult as ____core_common_17 } from './core/common';
import type { PhoneNumber as ____view_handlers_19 } from './view/handlers';
import type { PhoneNumberNormalizationResult as ____core_common_18 } from './core/common';
import type { PriceDisplayConfig as ____view_components_24 } from './view/components';
import type { RawReservationObject as ____core_common_19 } from './core/common';
import type { RawSheetRow as ____core_common_20 } from './core/common';
import type { RegistrationFormData as ____view_state_5 } from './view/state';
import type { RenderContext as ____view_components_25 } from './view/components';
import type { ReservationArrayData as ____core_common_21 } from './core/common';
import type { ReservationCacheData as ____core_common_22 } from './core/common';
import type { ReservationCore as ____core_reservation_0 } from './core/reservation';
import type { ReservationData as ____core_common_23 } from './core/common';
import type { ReservationFormContext as ____view_state_6 } from './view/state';
import type { ReservationId as ____view_handlers_20 } from './view/handlers';
import type { ReservationObject as ____core_common_24 } from './core/common';
import type { ReservationRawDataArray as ____core_common_25 } from './core/common';
import type { ReservationSearchResult as ____view_state_7 } from './view/state';
import type { SafeDOMElementAccess as ____view_dom_7 } from './view/dom';
import type { SafeElementAccess as ____view_dom_8 } from './view/dom';
import type { SafeElementGetter as ____view_dom_9 } from './view/dom';
import type { SalesBaseInfo as ____core_common_26 } from './core/common';
import type { SalesRowArray as ____core_common_27 } from './core/common';
import type { ScheduleCacheData as ____core_common_28 } from './core/common';
import type { ScheduleInfo as ____core_lesson_1 } from './core/lesson';
import type { ScheduleInfoParams as ____core_common_29 } from './core/common';
import type { ScheduleMasterData as ____core_common_30 } from './core/common';
import type { SelectConfig as ____view_components_26 } from './view/components';
import type { ServerResponse as ____core_common_31 } from './core/common';
import type { SessionCore as ____core_lesson_2 } from './core/lesson';
import type { SheetDataResult as ____core_common_32 } from './core/common';
import type { SheetSearchResult as ____core_common_33 } from './core/common';
import type { SideEffect as ____view_state_8 } from './view/state';
import type { SimpleStateManager as ____view_state_9 } from './view/state';
import type { StateAction as ____view_state_10 } from './view/state';
import type { StateActionPayload as ____view_state_11 } from './view/state';
import type { StateChange as ____view_state_12 } from './view/state';
import type { StateNavigationHistoryEntry as ____view_state_13 } from './view/state';
import type { StateSubscriber as ____view_state_14 } from './view/state';
import type { StateTrigger as ____view_state_15 } from './view/state';
import type { StateUpdatePattern as ____view_state_16 } from './view/state';
import type { StatusBadgeConfig as ____view_components_27 } from './view/components';
import type { StudentCacheData as ____core_common_34 } from './core/common';
import type { StudentData as ____core_common_35 } from './core/common';
import type { StudentId as ____view_handlers_21 } from './view/handlers';
import type { TextStyles as ____view_design-system_11 } from './view/design-system';
import type { TextareaConfig as ____view_components_28 } from './view/components';
import type { TimeString as ____view_handlers_22 } from './view/handlers';
import type { TransactionCallback as ____core_common_36 } from './core/common';
import type { TypedDocument as ____view_dom_10 } from './view/dom';
import type { TypedFormElements as ____view_dom_11 } from './view/dom';
import type { TypedHTMLFormElement as ____view_dom_12 } from './view/dom';
import type { TypedHTMLInputElement as ____view_dom_13 } from './view/dom';
import type { TypedHTMLSelectElement as ____view_dom_14 } from './view/dom';
import type { TypedHTMLTextAreaElement as ____view_dom_15 } from './view/dom';
import type { UIComponentFunction as ____view_components_29 } from './view/components';
import type { UIEventData as ____view_handlers_23 } from './view/handlers';
import type { UIState as ____view_state_17 } from './view/state';
import type { UnifiedApiResponse as ____core_common_37 } from './core/common';
import type { UserCore as ____core_user_0 } from './core/user';
import type { UserFormConfig as ____view_components_30 } from './view/components';
import type { UserInteraction as ____view_handlers_24 } from './view/handlers';
import type { UserProfileUpdateResult as ____core_common_38 } from './core/common';
import type { UtilStyles as ____view_design-system_12 } from './view/design-system';
import type { ViewGenerator as ____view_components_31 } from './view/components';
import type { ViewGeneratorWithConfig as ____view_components_32 } from './view/components';
import type { ViewType as ____view_state_18 } from './view/state';
import type { VoidCallback as ____view_handlers_25 } from './view/handlers';

declare global {
  type AccountingCacheData = ____core_common_0;
  type AccountingCalculationResult = ____view_handlers_0;
  type AccountingDetails = ____core_common_1;
  type AccountingDetailsCore = ____core_accounting_0;
  type AccountingFormDto = ____view_state_0;
  type AccountingMasterItem = ____core_common_2;
  type AccountingMasterItemCore = ____core_accounting_1;
  type AccountingRowConfig = ____view_components_0;
  type ActionButtonSectionConfig = ____view_components_1;
  type ActionHandler = ____view_handlers_1;
  type ActionHandlerData = ____view_handlers_2;
  type ActionHandlers = ____view_handlers_3;
  type ActionType = ____view_state_1;
  type ApiErrorResponse = ____core_common_3;
  type ApiResponse = ____core_common_4;
  type ApiResponseData = ____core_common_5;
  type ApiResponseGeneric = ____core_common_6;
  type ApiSuccessResponse = ____core_common_7;
  type AppInitialData = ____core_common_8;
  type AppState = ____view_state_2;
  type AsyncEventHandler = ____view_handlers_4;
  type AsyncGenericCallback = ____view_handlers_5;
  type AsyncVoidCallback = ____view_handlers_6;
  type BadgeType = ____view_components_2;
  type BatchDataPayload = ____core_common_9;
  type BatchDataResponse = ____core_common_10;
  type BatchDataResult = ____core_common_11;
  type ButtonConfig = ____view_components_3;
  type ButtonStyles = ____view_design-system_0;
  type CacheDataStructure = ____core_common_12;
  type CacheInfo = ____core_common_13;
  type CardContainerConfig = ____view_components_4;
  type CardHistoryConfig = ____view_design-system_1;
  type CardStateConfig = ____view_design-system_2;
  type CardStates = ____view_design-system_3;
  type CardStyles = ____view_design-system_4;
  type ChangeEventHandler = ____view_handlers_7;
  type CheckboxConfig = ____view_components_5;
  type ChunkedCacheMetadata = ____core_common_14;
  type ClassifiedAccountingItemsCore = ____core_accounting_2;
  type ClassroomColorConfig = ____view_design-system_5;
  type ClassroomColors = ____view_design-system_6;
  type ClassroomName = ____view_handlers_8;
  type ClickEventHandler = ____view_handlers_9;
  type ComponentConfig = ____view_components_6;
  type ComponentFunction = ____view_components_7;
  type ComponentProps = ____view_components_8;
  type ComponentQuerySelector = ____view_dom_0;
  type ComponentQuerySelectorAll = ____view_dom_1;
  type ComponentRenderer = ____view_components_9;
  type ComponentSize = ____view_components_10;
  type ComponentStyle = ____view_components_11;
  type ComputedStateData = ____view_state_3;
  type ConfirmDialogConfig = ____view_components_12;
  type DOMElementSafeAccess = ____view_dom_2;
  type DashboardSectionConfig = ____view_components_13;
  type DateString = ____view_handlers_10;
  type DesignColors = ____view_design-system_7;
  type DesignSystemConfig = ____view_design-system_8;
  type DocumentWithTypedElements = ____view_dom_3;
  type ElementWithCommonProperties = ____view_dom_4;
  type ErrorHandler = ____view_handlers_11;
  type ErrorInfo = ____core_common_15;
  type EventHandler = ____view_handlers_12;
  type EventHandlerFunction = ____view_handlers_13;
  type FormEventHandler = ____view_handlers_14;
  type FrontendErrorHandlerClass = ____view_handlers_15;
  type FrontendErrorInfo = ____view_handlers_16;
  type GenericCallback = ____view_handlers_17;
  type HTMLElementEventListeners = ____view_dom_5;
  type HTMLElementWithId = ____view_dom_6;
  type HTMLGeneratorFunction = ____view_components_14;
  type HTMLString = ____view_components_15;
  type HeaderMapType = ____core_common_16;
  type InputConfig = ____view_components_16;
  type InputEventHandler = ____view_handlers_18;
  type InputStyles = ____view_design-system_9;
  type LayoutStyles = ____view_design-system_10;
  type LessonCore = ____core_lesson_0;
  type ListCardConfig = ____view_components_17;
  type MaterialRowConfig = ____view_components_18;
  type MemoSectionConfig = ____view_components_19;
  type ModalConfig = ____view_components_20;
  type ModalDialogConfig = ____view_components_21;
  type NavigationContext = ____view_state_4;
  type OtherSalesRowConfig = ____view_components_22;
  type PageContainerConfig = ____view_components_23;
  type PhoneNormalizationResult = ____core_common_17;
  type PhoneNumber = ____view_handlers_19;
  type PhoneNumberNormalizationResult = ____core_common_18;
  type PriceDisplayConfig = ____view_components_24;
  type RawReservationObject = ____core_common_19;
  type RawSheetRow = ____core_common_20;
  type RegistrationFormData = ____view_state_5;
  type RenderContext = ____view_components_25;
  type ReservationArrayData = ____core_common_21;
  type ReservationCacheData = ____core_common_22;
  type ReservationCore = ____core_reservation_0;
  type ReservationData = ____core_common_23;
  type ReservationFormContext = ____view_state_6;
  type ReservationId = ____view_handlers_20;
  type ReservationObject = ____core_common_24;
  type ReservationRawDataArray = ____core_common_25;
  type ReservationSearchResult = ____view_state_7;
  type SafeDOMElementAccess = ____view_dom_7;
  type SafeElementAccess = ____view_dom_8;
  type SafeElementGetter = ____view_dom_9;
  type SalesBaseInfo = ____core_common_26;
  type SalesRowArray = ____core_common_27;
  type ScheduleCacheData = ____core_common_28;
  type ScheduleInfo = ____core_lesson_1;
  type ScheduleInfoParams = ____core_common_29;
  type ScheduleMasterData = ____core_common_30;
  type SelectConfig = ____view_components_26;
  type ServerResponse = ____core_common_31;
  type SessionCore = ____core_lesson_2;
  type SheetDataResult = ____core_common_32;
  type SheetSearchResult = ____core_common_33;
  type SideEffect = ____view_state_8;
  type SimpleStateManager = ____view_state_9;
  type StateAction = ____view_state_10;
  type StateActionPayload = ____view_state_11;
  type StateChange = ____view_state_12;
  type StateNavigationHistoryEntry = ____view_state_13;
  type StateSubscriber = ____view_state_14;
  type StateTrigger = ____view_state_15;
  type StateUpdatePattern = ____view_state_16;
  type StatusBadgeConfig = ____view_components_27;
  type StudentCacheData = ____core_common_34;
  type StudentData = ____core_common_35;
  type StudentId = ____view_handlers_21;
  type TextStyles = ____view_design-system_11;
  type TextareaConfig = ____view_components_28;
  type TimeString = ____view_handlers_22;
  type TransactionCallback = ____core_common_36;
  type TypedDocument = ____view_dom_10;
  type TypedFormElements = ____view_dom_11;
  type TypedHTMLFormElement = ____view_dom_12;
  type TypedHTMLInputElement = ____view_dom_13;
  type TypedHTMLSelectElement = ____view_dom_14;
  type TypedHTMLTextAreaElement = ____view_dom_15;
  type UIComponentFunction = ____view_components_29;
  type UIEventData = ____view_handlers_23;
  type UIState = ____view_state_17;
  type UnifiedApiResponse = ____core_common_37;
  type UserCore = ____core_user_0;
  type UserFormConfig = ____view_components_30;
  type UserInteraction = ____view_handlers_24;
  type UserProfileUpdateResult = ____core_common_38;
  type UtilStyles = ____view_design-system_12;
  type ViewGenerator = ____view_components_31;
  type ViewGeneratorWithConfig = ____view_components_32;
  type ViewType = ____view_state_18;
  type VoidCallback = ____view_handlers_25;
}

export {};
