/**
 * =================================================================
 * 【ファイル名】: 00_Constants.js
 * 【バージョン】: 1.1
 * 【役割】: プロジェクト全体で使用する統一定数定義システム
 *
 * 【主要機能】:
 * ✅ 統一定数管理
 *   - 教室名、ヘッダー名、項目名、ステータス等の一元管理
 *   - フロントエンドとバックエンド間での定数重複を完全解消
 *   - 階層構造による論理的な定数分類（CONSTANTS オブジェクト）
 *
 * ✅ 後方互換性システム
 *   - 既存コードとの互換性を保つための後方互換性定数
 *   - 段階的移行を可能にする設計
 *   - 全33ヘッダー、項目名、ステータス等の完全対応
 *
 * ✅ 真実の情報源（Single Source of Truth）
 *   - 定数変更時の一箇所修正で全体反映
 *   - 定数の不整合や同期漏れを完全排除
 *   - 開発効率と保守性の大幅向上
 *
 * 【v1.1での変更点】:
 * - フェーズ1リファクタリング完了: 全定数の統一管理を実現
 * - 完全なヘッダー後方互換性対応（全33ヘッダー）
 * - 01_Code.js との重複定義完全解消
 * - 階層構造による論理的定数分類の確立
 * - 統一定数アクセスパターンの標準化
 *
 * 【構成】: 18ファイル構成のうちの0番目（新規追加、基盤ファイル）
 * 【依存関係】: なし（他の全ファイルがこのファイルに依存）
 * =================================================================
 */

/**
 * プロジェクト全体で使用する統一定数オブジェクト
 * 階層構造により論理的に分類された定数を管理
 */
const CONSTANTS = {
  // 教室名
  CLASSROOMS: {
    TOKYO: '東京教室',
    NUMAZU: '沼津教室',
    TSUKUBA: 'つくば教室',
  },

  // 教室定員
  CLASSROOM_CAPACITIES: {
    東京教室: 8,
    沼津教室: 8,
    つくば教室: 8,
  },

  // ヘッダー名
  HEADERS: {
    STUDENT_ID: '生徒ID',
    RESERVATION_ID: '予約ID',
    DATE: '日付',
    VENUE: '会場',
    PARTICIPANT_COUNT: '人数',
    CO: 'co',
    NAME: '名前',
    CLASS_COUNT: '回数',
    UNIFIED_CLASS_COUNT: '参加回数',
    FIRST_LECTURE: '初講',
    CHISEL_RENTAL: '彫刻刀レンタル',
    TIME: '受講時間',
    WORK_IN_PROGRESS: '制作メモ',
    ORDER: 'order',
    MESSAGE_TO_TEACHER: 'メッセージ',
    ACCOUNTING_DETAILS: '会計詳細',
    LINE: 'LINE',
    IN_THE_FUTURE: 'in the future',
    NOTES: 'notes',
    FROM: 'from',
    CLASS_START: '講座開始',
    CLASS_END: '講座終了',
    BREAK_START: '休憩開始',
    BREAK_END: '休憩終了',
    START_TIME: '開始時刻',
    END_TIME: '終了時刻',
    CLASSROOM: '教室',
    STATUS: 'ステータス',
    TRANSPORTATION: '来場手段',
    PICKUP: '送迎',
    REAL_NAME: '本名',
    NICKNAME: 'ニックネーム',
    PHONE: '電話番号',
  },

  // 項目名
  ITEMS: {
    MAIN_LECTURE: '本講座',
    FIRST_LECTURE: '初回講習',
    CHISEL_RENTAL: '彫刻刀レンタル',
    TOOL_SET: '道具セット',
    MATERIAL_FEE: '材料費',
    DISCOUNT: '初回講習同時間割引',
  },

  // ステータス（4種類統合定数）
  STATUS: {
    CANCELED: 'canceled', // キャンセル済み
    WAITLISTED: 'waitlisted', // キャンセル待ち
    CONFIRMED: 'confirmed', // 予約確定（会計前）
    COMPLETED: 'completed', // 完了（会計済み）
    // 後方互換性のため旧定数も保持
    WAITING: 'waitlisted', // 旧WAITING → waitlisted
    CANCEL: 'canceled', // 旧CANCEL → canceled
  },

  // 項目種別
  ITEM_TYPES: {
    TUITION: '授業料',
    SALES: '物販',
    MATERIAL: '材料',
  },

  // 単位
  UNITS: {
    THIRTY_MIN: '30分',
    PIECE: '個',
    SET: 'セット',
    CM3: 'cm³',
  },

  // 支払い方法
  PAYMENT_METHODS: {
    CASH: 'cash',
    CARD: 'card',
    TRANSFER: 'transfer',
  },

  // UI関連の定数
  UI: {
    HISTORY_INITIAL_RECORDS: 10,
    HISTORY_LOAD_MORE_RECORDS: 10,
    LOADING_MESSAGE_INTERVAL: 2000,
    MODAL_FADE_DURATION: 300,
  },

  // 容量・制限
  LIMITS: {
    INTRO_LECTURE_CAPACITY: 4,
    TSUKUBA_MORNING_SESSION_END_HOUR: 13,
    LOCK_WAIT_TIME_MS: 30000,
    MAX_RETRY_COUNT: 3,
  },

  // シート名
  SHEET_NAMES: {
    ROSTER: '生徒名簿',
    ACCOUNTING_MASTER: '会計マスタ',
    LOG: 'アクティビティログ',
    INTEGRATED_RESERVATIONS: '統合予約シート',
    SCHEDULE_MASTER: '日程マスタ',
  },

  // セッション関連
  SESSIONS: {
    MORNING: '午前',
    AFTERNOON: '午後',
    ALL_DAY: '全日',
  },

  // 支払い方法（表示用）
  PAYMENT_DISPLAY: {
    CASH: '現金',
    COTRA: 'ことら送金',
    BANK_TRANSFER: '振込',
  },

  // 銀行情報
  BANK_INFO: {
    COTRA_PHONE: '09013755977',
    NAME: 'ゆうちょ銀行',
    BRANCH: '818',
    ACCOUNT: '2661797',
  },

  // フロントエンド固有のUI設定
  FRONTEND_UI: {
    DISCOUNT_OPTIONS: {
      NONE: 0,
      THIRTY_MIN: 30,
      SIXTY_MIN: 60,
    },
    TIME_SETTINGS: {
      STEP_MINUTES: 30,
      END_BUFFER_HOURS: 3,
    },
  },

  // メッセージ定数
  MESSAGES: {
    PROCESSING_INTERRUPTED: '処理を中断しました。',
    SHEET_INITIALIZATION: '日程マスタシートの初期化',
    EXISTING_SHEET_WARNING:
      '「日程マスタ」シートは既に存在します。\n初期化しますか？（既存データは削除されます）',
    SUCCESS: '成功',
    ERROR: 'エラー',
    CANCEL: 'キャンセル',
  },

  // ログアクション定数
  LOG_ACTIONS: {
    ROSTER_EDIT: '名簿編集',
    RESERVATION_EDIT: '予約編集',
    ROW_INSERT: '行挿入',
    RESERVATION_CANCEL: '予約キャンセル',
  },

  // 表示色定数
  COLORS: {
    LIGHT_GREEN: '#d9ead3', // 成功
    LIGHT_RED: '#f4cccc', // 失敗・エラー
    LIGHT_BLUE: '#cfe2f3', // ユーザーの主要アクション
    LIGHT_ORANGE: '#fce5cd', // 編集・変更系アクション
    HEADER_BACKGROUND: '#E8F0FE', // ヘッダーの背景色
  },

  // 教室タイプ定数
  CLASSROOM_TYPES: {
    SESSION_BASED: 'セッション制',
    TIME_DUAL: '時間制・2部制',
    TIME_FULL: '時間制・全日',
  },

  // スケジュールステータス定数
  SCHEDULE_STATUS: {
    SCHEDULED: '開催予定',
    CANCELLED: '休講',
    COMPLETED: '開催済み',
  },

  // スケジュールヘッダー定数（日程マスタ専用）
  SCHEDULE_HEADERS: {
    DATE: '日付',
    CLASSROOM: '教室',
    VENUE: '会場',
    TYPE: '教室形式',
    FIRST_START: '1部開始',
    FIRST_END: '1部終了',
    SECOND_START: '2部開始',
    SECOND_END: '2部終了',
    BEGINNER_START: '初心者開始',
    TOTAL_CAPACITY: '全体定員',
    BEGINNER_CAPACITY: '初心者定員',
    STATUS: '状態',
    NOTES: '備考',
  },

  // その他のシステム定数
  SYSTEM: {
    MATERIAL_INFO_PREFIX: '\n【希望材料】: ',
    ARCHIVE_PREFIX: 'アーカイブ_',
    DATA_START_ROW: 2,
  },
};

// =================================================================
// 後方互換性定数システム
//
// 【目的】: 既存コードとの互換性を保ちながら段階的に統一定数へ移行
// 【方針】: CONSTANTS オブジェクトから値を継承する形で後方互換性を確保
// 【対象】: 全プロジェクトで使用されている既存定数名
// 【利点】: 一箇所変更で全体反映、段階的移行が可能
// =================================================================

// 教室名の後方互換性
const TOKYO_CLASSROOM_NAME = CONSTANTS.CLASSROOMS.TOKYO;
const NUMAZU_CLASSROOM_NAME = CONSTANTS.CLASSROOMS.NUMAZU;
const TSUKUBA_CLASSROOM_NAME = CONSTANTS.CLASSROOMS.TSUKUBA;
const CLASSROOM_SHEET_NAMES = [
  CONSTANTS.CLASSROOMS.TOKYO,
  CONSTANTS.CLASSROOMS.NUMAZU,
  CONSTANTS.CLASSROOMS.TSUKUBA,
];
const CLASSROOM_CAPACITIES = CONSTANTS.CLASSROOM_CAPACITIES;

// 制限値の後方互換性
const INTRO_LECTURE_CAPACITY = CONSTANTS.LIMITS.INTRO_LECTURE_CAPACITY;
const TSUKUBA_MORNING_SESSION_END_HOUR =
  CONSTANTS.LIMITS.TSUKUBA_MORNING_SESSION_END_HOUR;
const LOCK_WAIT_TIME_MS = CONSTANTS.LIMITS.LOCK_WAIT_TIME_MS;

// シート名の後方互換性
const ROSTER_SHEET_NAME = CONSTANTS.SHEET_NAMES.ROSTER;
const ACCOUNTING_MASTER_SHEET_NAME = CONSTANTS.SHEET_NAMES.ACCOUNTING_MASTER;
const LOG_SHEET_NAME = CONSTANTS.SHEET_NAMES.LOG;

// ヘッダー名の後方互換性（全ヘッダー対応）
const HEADER_STUDENT_ID = CONSTANTS.HEADERS.STUDENT_ID;
const HEADER_RESERVATION_ID = CONSTANTS.HEADERS.RESERVATION_ID;
const HEADER_DATE = CONSTANTS.HEADERS.DATE;
const HEADER_VENUE = CONSTANTS.HEADERS.VENUE;
const HEADER_FIRST_LECTURE = CONSTANTS.HEADERS.FIRST_LECTURE;
const HEADER_CHISEL_RENTAL = CONSTANTS.HEADERS.CHISEL_RENTAL;
const HEADER_START_TIME = CONSTANTS.HEADERS.START_TIME;
const HEADER_END_TIME = CONSTANTS.HEADERS.END_TIME;
const HEADER_CLASS_START = CONSTANTS.HEADERS.CLASS_START;
const HEADER_CLASS_END = CONSTANTS.HEADERS.CLASS_END;
const HEADER_BREAK_START = CONSTANTS.HEADERS.BREAK_START;
const HEADER_BREAK_END = CONSTANTS.HEADERS.BREAK_END;
const HEADER_CLASSROOM = CONSTANTS.HEADERS.CLASSROOM;
const HEADER_STATUS = CONSTANTS.HEADERS.STATUS;
const HEADER_REAL_NAME = CONSTANTS.HEADERS.REAL_NAME;
const HEADER_NICKNAME = CONSTANTS.HEADERS.NICKNAME;
const HEADER_PHONE = CONSTANTS.HEADERS.PHONE;
const HEADER_CO = CONSTANTS.HEADERS.CO;
const HEADER_PARTICIPANT_COUNT = CONSTANTS.HEADERS.PARTICIPANT_COUNT;
const HEADER_NAME = CONSTANTS.HEADERS.NAME;
const HEADER_CLASS_COUNT = CONSTANTS.HEADERS.CLASS_COUNT;
const HEADER_UNIFIED_CLASS_COUNT = CONSTANTS.HEADERS.UNIFIED_CLASS_COUNT;
const HEADER_TIME = CONSTANTS.HEADERS.TIME;
const HEADER_WORK_IN_PROGRESS = CONSTANTS.HEADERS.WORK_IN_PROGRESS;
const HEADER_ORDER = CONSTANTS.HEADERS.ORDER;
const HEADER_MESSAGE_TO_TEACHER = CONSTANTS.HEADERS.MESSAGE_TO_TEACHER;
const HEADER_ACCOUNTING_DETAILS = CONSTANTS.HEADERS.ACCOUNTING_DETAILS;
const HEADER_LINE = CONSTANTS.HEADERS.LINE;
const HEADER_IN_THE_FUTURE = CONSTANTS.HEADERS.IN_THE_FUTURE;
const HEADER_NOTES = CONSTANTS.HEADERS.NOTES;
const HEADER_FROM = CONSTANTS.HEADERS.FROM;
const HEADER_TRANSPORTATION = CONSTANTS.HEADERS.TRANSPORTATION;
const HEADER_PICKUP = CONSTANTS.HEADERS.PICKUP;

// 項目名の後方互換性
const ITEM_NAME_MAIN_LECTURE = CONSTANTS.ITEMS.MAIN_LECTURE;
const ITEM_NAME_FIRST_LECTURE = CONSTANTS.ITEMS.FIRST_LECTURE;
const ITEM_NAME_CHISEL_RENTAL = CONSTANTS.ITEMS.CHISEL_RENTAL;
const ITEM_NAME_DISCOUNT = CONSTANTS.ITEMS.DISCOUNT;

// ステータス（新統合定数）
const STATUS_CANCELED = CONSTANTS.STATUS.CANCELED;
const STATUS_WAITLISTED = CONSTANTS.STATUS.WAITLISTED;
const STATUS_CONFIRMED = CONSTANTS.STATUS.CONFIRMED;
const STATUS_COMPLETED = CONSTANTS.STATUS.COMPLETED;

// ステータスの後方互換性
const STATUS_WAITING = CONSTANTS.STATUS.WAITING;
const STATUS_CANCEL = CONSTANTS.STATUS.CANCEL;

// 項目種別の後方互換性
const ITEM_TYPE_TUITION = CONSTANTS.ITEM_TYPES.TUITION;
const ITEM_TYPE_SALES = CONSTANTS.ITEM_TYPES.SALES;
const ITEM_TYPE_MATERIAL = CONSTANTS.ITEM_TYPES.MATERIAL;

// 単位の後方互換性
const UNIT_30_MIN = CONSTANTS.UNITS.THIRTY_MIN;
const UNIT_CM3 = CONSTANTS.UNITS.CM3;

// 支払い方法の後方互換性
const PAYMENT_CASH = CONSTANTS.PAYMENT_METHODS.CASH;

// セッションの後方互換性
const SESSION_MORNING = CONSTANTS.SESSIONS.MORNING;
const SESSION_AFTERNOON = CONSTANTS.SESSIONS.AFTERNOON;
const SESSION_ALL_DAY = CONSTANTS.SESSIONS.ALL_DAY;

// 支払い方法表示の後方互換性
const PAYMENT_COTRA = CONSTANTS.PAYMENT_DISPLAY.COTRA;
const PAYMENT_BANK_TRANSFER = CONSTANTS.PAYMENT_DISPLAY.BANK_TRANSFER;

// 銀行情報の後方互換性
const BANK_COTRA_PHONE = CONSTANTS.BANK_INFO.COTRA_PHONE;
const BANK_NAME = CONSTANTS.BANK_INFO.NAME;
const BANK_BRANCH = CONSTANTS.BANK_INFO.BRANCH;
const BANK_ACCOUNT = CONSTANTS.BANK_INFO.ACCOUNT;

// フロントエンドUI定数の後方互換性
const DISCOUNT_OPTION_NONE = CONSTANTS.FRONTEND_UI.DISCOUNT_OPTIONS.NONE;
const DISCOUNT_OPTION_30MIN = CONSTANTS.FRONTEND_UI.DISCOUNT_OPTIONS.THIRTY_MIN;
const DISCOUNT_OPTION_60MIN = CONSTANTS.FRONTEND_UI.DISCOUNT_OPTIONS.SIXTY_MIN;
const TIME_STEP_MINUTES = CONSTANTS.FRONTEND_UI.TIME_SETTINGS.STEP_MINUTES;
const TIME_END_BUFFER_HOURS =
  CONSTANTS.FRONTEND_UI.TIME_SETTINGS.END_BUFFER_HOURS;

// UI定数の後方互換性
const UI_HISTORY_INITIAL_RECORDS = CONSTANTS.UI.HISTORY_INITIAL_RECORDS;
const UI_HISTORY_LOAD_MORE_RECORDS = CONSTANTS.UI.HISTORY_LOAD_MORE_RECORDS;
const UI_LOADING_MESSAGE_INTERVAL = CONSTANTS.UI.LOADING_MESSAGE_INTERVAL;

// メッセージ定数の後方互換性
const MSG_PROCESSING_INTERRUPTED = CONSTANTS.MESSAGES.PROCESSING_INTERRUPTED;
const MSG_SHEET_INITIALIZATION = CONSTANTS.MESSAGES.SHEET_INITIALIZATION;
const MSG_EXISTING_SHEET_WARNING = CONSTANTS.MESSAGES.EXISTING_SHEET_WARNING;
const MSG_SUCCESS = CONSTANTS.MESSAGES.SUCCESS;
const MSG_ERROR = CONSTANTS.MESSAGES.ERROR;
const MSG_CANCEL = CONSTANTS.MESSAGES.CANCEL;

// ログアクション定数の後方互換性
const LOG_ACTION_ROSTER_EDIT = CONSTANTS.LOG_ACTIONS.ROSTER_EDIT;
const LOG_ACTION_RESERVATION_EDIT = CONSTANTS.LOG_ACTIONS.RESERVATION_EDIT;
const LOG_ACTION_ROW_INSERT = CONSTANTS.LOG_ACTIONS.ROW_INSERT;
const LOG_ACTION_RESERVATION_CANCEL = CONSTANTS.LOG_ACTIONS.RESERVATION_CANCEL;

// 表示色定数の後方互換性
const COLOR_LIGHT_GREEN = CONSTANTS.COLORS.LIGHT_GREEN;
const COLOR_LIGHT_RED = CONSTANTS.COLORS.LIGHT_RED;
const COLOR_LIGHT_BLUE = CONSTANTS.COLORS.LIGHT_BLUE;
const COLOR_LIGHT_ORANGE = CONSTANTS.COLORS.LIGHT_ORANGE;
const COLOR_HEADER_BACKGROUND = CONSTANTS.COLORS.HEADER_BACKGROUND;

// 教室タイプ定数の後方互換性
const CLASSROOM_TYPE_SESSION_BASED = CONSTANTS.CLASSROOM_TYPES.SESSION_BASED;
const CLASSROOM_TYPE_TIME_DUAL = CONSTANTS.CLASSROOM_TYPES.TIME_DUAL;
const CLASSROOM_TYPE_TIME_FULL = CONSTANTS.CLASSROOM_TYPES.TIME_FULL;

// スケジュールステータス定数の後方互換性
const SCHEDULE_STATUS_SCHEDULED = CONSTANTS.SCHEDULE_STATUS.SCHEDULED;
const SCHEDULE_STATUS_CANCELLED = CONSTANTS.SCHEDULE_STATUS.CANCELLED;
const SCHEDULE_STATUS_COMPLETED = CONSTANTS.SCHEDULE_STATUS.COMPLETED;

// スケジュールヘッダー定数の後方互換性
const HEADER_SCHEDULE_DATE = CONSTANTS.SCHEDULE_HEADERS.DATE;
const HEADER_SCHEDULE_CLASSROOM = CONSTANTS.SCHEDULE_HEADERS.CLASSROOM;
const HEADER_SCHEDULE_VENUE = CONSTANTS.SCHEDULE_HEADERS.VENUE;
const HEADER_SCHEDULE_TYPE = CONSTANTS.SCHEDULE_HEADERS.TYPE;
const HEADER_SCHEDULE_FIRST_START = CONSTANTS.SCHEDULE_HEADERS.FIRST_START;
const HEADER_SCHEDULE_FIRST_END = CONSTANTS.SCHEDULE_HEADERS.FIRST_END;
const HEADER_SCHEDULE_SECOND_START = CONSTANTS.SCHEDULE_HEADERS.SECOND_START;
const HEADER_SCHEDULE_SECOND_END = CONSTANTS.SCHEDULE_HEADERS.SECOND_END;
const HEADER_SCHEDULE_BEGINNER_START =
  CONSTANTS.SCHEDULE_HEADERS.BEGINNER_START;
const HEADER_SCHEDULE_TOTAL_CAPACITY =
  CONSTANTS.SCHEDULE_HEADERS.TOTAL_CAPACITY;
const HEADER_SCHEDULE_BEGINNER_CAPACITY =
  CONSTANTS.SCHEDULE_HEADERS.BEGINNER_CAPACITY;
const HEADER_SCHEDULE_STATUS = CONSTANTS.SCHEDULE_HEADERS.STATUS;
const HEADER_SCHEDULE_NOTES = CONSTANTS.SCHEDULE_HEADERS.NOTES;

// その他のシステム定数の後方互換性
const MATERIAL_INFO_PREFIX = CONSTANTS.SYSTEM.MATERIAL_INFO_PREFIX;
const HEADER_ARCHIVE_PREFIX = CONSTANTS.SYSTEM.ARCHIVE_PREFIX;
const DATA_START_ROW = CONSTANTS.SYSTEM.DATA_START_ROW;

// 実行時取得定数
const SALES_SPREADSHEET_ID =
  PropertiesService.getScriptProperties().getProperty('SALES_SPREADSHEET_ID');
