/**
 * @file This file is auto-generated by tools/create-global-bridge.js.
 * Do not edit this file manually.
 */

declare global {
  const CONSTANTS: {
    readonly TIMEZONE: string;
    readonly ENVIRONMENT: {
      readonly PRODUCTION_MODE: boolean;
      readonly APP_VERSION: string;
    };
    readonly WEB_APP_URL: {
      readonly PRODUCTION: string;
    };
    readonly CLASSROOMS: {
      readonly TOKYO: string;
      readonly NUMAZU: string;
      readonly TSUKUBA: string;
    };
    readonly STATUS: {
      readonly CANCELED: string;
      readonly WAITLISTED: string;
      readonly CONFIRMED: string;
      readonly COMPLETED: string;
    };
    readonly STATUS_PRIORITY: {
      readonly 完了: number;
      readonly 確定: number;
      readonly 待機: number;
      readonly 取消: number;
    };
    readonly UNITS: {
      readonly THIRTY_MIN: string;
      readonly PIECE: string;
      readonly SET: string;
      readonly CM3: string;
    };
    readonly PAYMENT_METHODS: {
      readonly CASH: string;
      readonly CARD: string;
      readonly TRANSFER: string;
    };
    readonly UI: {
      readonly HISTORY_INITIAL_RECORDS: number;
      readonly HISTORY_LOAD_MORE_RECORDS: number;
      readonly LOADING_MESSAGE_INTERVAL: number;
      readonly MODAL_FADE_DURATION: number;
      readonly COLUMN_WIDTHS: {
        readonly DATE: number;
        readonly CLASSROOM: number;
        readonly VENUE: number;
        readonly CLASSROOM_TYPE: number;
        readonly TIME: number;
        readonly BEGINNER_START: number;
        readonly CAPACITY: number;
        readonly STATUS: number;
        readonly NOTES: number;
      };
    };
    readonly LIMITS: {
      readonly TSUKUBA_MORNING_SESSION_END_HOUR: number;
      readonly LOCK_WAIT_TIME_MS: number;
      readonly MAX_RETRY_COUNT: number;
    };
    readonly SHEET_NAMES: {
      readonly ROSTER: string;
      readonly ACCOUNTING: string;
      readonly LOG: string;
      readonly RESERVATIONS: string;
      readonly SCHEDULE: string;
      readonly SALES_LOG: string;
    };
    readonly TIME_SLOTS: {
      readonly MORNING: string;
      readonly AFTERNOON: string;
      readonly ALL_DAY: string;
    };
    readonly PAYMENT_DISPLAY: {
      readonly CASH: string;
      readonly COTRA: string;
      readonly BANK_TRANSFER: string;
    };
    readonly BANK_INFO: {
      readonly COTRA_PHONE: string;
      readonly NAME: string;
      readonly BRANCH: string;
      readonly ACCOUNT: string;
    };
    readonly FRONTEND_UI: {
      readonly DISCOUNT_OPTIONS: {
        readonly NONE: number;
        readonly THIRTY_MIN: number;
        readonly SIXTY_MIN: number;
      };
      readonly TIME_SETTINGS: {
        readonly STEP_MINUTES: number;
        readonly END_BUFFER_HOURS: number;
      };
    };
    readonly MESSAGES: {
      readonly PROCESSING_INTERRUPTED: string;
      readonly SHEET_INITIALIZATION: string;
      readonly EXISTING_SHEET_WARNING: string;
      readonly SUCCESS: string;
      readonly ERROR: string;
      readonly CANCEL: string;
      readonly SAVE: string;
      readonly EDIT: string;
    };
    readonly LOG_ACTIONS: {
      readonly RESERVATION_CREATE: string;
      readonly RESERVATION_CREATE_DATE_CHANGE: string;
      readonly RESERVATION_WAITLIST: string;
      readonly RESERVATION_CANCEL: string;
      readonly RESERVATION_CANCEL_DATE_CHANGE: string;
      readonly RESERVATION_UPDATE: string;
      readonly RESERVATION_CONFIRM: string;
      readonly RESERVATION_EDIT: string;
      readonly ACCOUNTING_SAVE: string;
      readonly ACCOUNTING_MODIFY: string;
      readonly USER_LOGIN: string;
      readonly USER_LOGOUT: string;
      readonly USER_REGISTER: string;
      readonly USER_UPDATE: string;
      readonly USER_GOAL_UPDATE: string;
      readonly USER_UPDATE_ERROR: string;
      readonly USER_PASSWORD_CHANGE: string;
      readonly USER_WITHDRAWAL: string;
      readonly USER_MESSAGE_SENT: string;
      readonly ADMIN_TOKEN_ISSUE: string;
      readonly ADMIN_TOKEN_VALIDATE_ERROR: string;
      readonly ADMIN_TOKEN_REVOKE: string;
      readonly ROSTER_EDIT: string;
      readonly ROW_INSERT: string;
      readonly EMAIL_VACANCY_NOTIFICATION: string;
      readonly BATCH_SALES_TRANSFER_START: string;
      readonly BATCH_SALES_TRANSFER_SUCCESS: string;
      readonly BATCH_SALES_TRANSFER_ERROR: string;
      readonly BATCH_SORT_SUCCESS: string;
      readonly BATCH_SORT_ERROR: string;
      readonly SYSTEM_ERROR: string;
    };
    readonly CLASSROOM_TYPES: {
      readonly SESSION_BASED: string;
      readonly TIME_DUAL: string;
      readonly TIME_FULL: string;
    };
    readonly SCHEDULE_STATUS: {
      readonly SCHEDULED: string;
      readonly CANCELLED: string;
      readonly COMPLETED: string;
    };
    readonly HEADERS: {
      readonly RESERVATIONS: {
        readonly RESERVATION_ID: string;
        readonly LESSON_ID: string;
        readonly STUDENT_ID: string;
        readonly DATE: string;
        readonly CLASSROOM: string;
        readonly VENUE: string;
        readonly START_TIME: string;
        readonly END_TIME: string;
        readonly STATUS: string;
        readonly CHISEL_RENTAL: string;
        readonly FIRST_LECTURE: string;
        readonly TRANSPORTATION: string;
        readonly PICKUP: string;
        readonly SESSION_NOTE: string;
        readonly ORDER: string;
        readonly MESSAGE_TO_TEACHER: string;
        readonly ACCOUNTING_DETAILS: string;
      };
      readonly ROSTER: {
        readonly STUDENT_ID: string;
        readonly REAL_NAME: string;
        readonly NICKNAME: string;
        readonly PHONE: string;
        readonly CAR: string;
        readonly CHISEL_RENTAL: string;
        readonly LINE: string;
        readonly NOTES: string;
        readonly FROM: string;
        readonly REGISTRATION_DATE: string;
        readonly EMAIL: string;
        readonly WANTS_RESERVATION_EMAIL: string;
        readonly WANTS_SCHEDULE_INFO: string;
        readonly NOTIFICATION_DAY: string;
        readonly NOTIFICATION_HOUR: string;
        readonly AGE_GROUP: string;
        readonly GENDER: string;
        readonly DOMINANT_HAND: string;
        readonly ADDRESS: string;
        readonly FUTURE_CREATIONS: string;
        readonly EXPERIENCE: string;
        readonly PAST_WORK: string;
        readonly ATTENDANCE_INTENTION: string;
        readonly TRIGGER: string;
        readonly FIRST_MESSAGE: string;
        readonly COMPANION: string;
        readonly TRANSPORTATION: string;
        readonly PICKUP: string;
        readonly TOTAL_PARTICIPATION: string;
        readonly NEXT_LESSON_GOAL: string;
      };
      readonly ACCOUNTING: {
        readonly TYPE: string;
        readonly ITEM_NAME: string;
        readonly UNIT_PRICE: string;
        readonly UNIT: string;
        readonly TARGET_CLASSROOM: string;
        readonly NOTES: string;
      };
      readonly SCHEDULE: {
        readonly LESSON_ID: string;
        readonly RESERVATION_IDS: string;
        readonly DATE: string;
        readonly CLASSROOM: string;
        readonly VENUE: string;
        readonly TYPE: string;
        readonly FIRST_START: string;
        readonly FIRST_END: string;
        readonly SECOND_START: string;
        readonly SECOND_END: string;
        readonly BEGINNER_START: string;
        readonly TOTAL_CAPACITY: string;
        readonly BEGINNER_CAPACITY: string;
        readonly STATUS: string;
        readonly NOTES: string;
      };
      readonly SALES_LOG: {
        readonly DATE: string;
        readonly CLASSROOM: string;
        readonly VENUE: string;
        readonly STUDENT_ID: string;
        readonly NAME: string;
        readonly CATEGORY: string;
        readonly ITEM_NAME: string;
        readonly UNIT_PRICE: string;
        readonly QUANTITY: string;
        readonly TOTAL: string;
        readonly PAYMENT_METHOD: string;
      };
      readonly LOG: {
        readonly TIMESTAMP: string;
        readonly USER_ID: string;
        readonly REAL_NAME: string;
        readonly NICKNAME: string;
        readonly ACTION: string;
        readonly RESULT: string;
        readonly CLASSROOM: string;
        readonly RESERVATION_ID: string;
        readonly DATE: string;
        readonly MESSAGE: string;
        readonly DETAILS: string;
      };
    };
    readonly ITEMS: {
      readonly MAIN_LECTURE: string;
      readonly MAIN_LECTURE_COUNT: string;
      readonly MAIN_LECTURE_TIME: string;
      readonly FIRST_LECTURE: string;
      readonly CHISEL_RENTAL: string;
      readonly DISCOUNT: string;
    };
    readonly ITEM_TYPES: {
      readonly TUITION: string;
      readonly SALES: string;
      readonly MATERIAL: string;
    };
    readonly SYSTEM: {
      readonly MATERIAL_INFO_PREFIX: string;
      readonly ARCHIVE_PREFIX: string;
      readonly DATA_START_ROW: number;
      readonly CACHE_EXPIRY_SECONDS: number;
      readonly HEADER_ROW: number;
    };
    readonly ACCOUNTING_SYSTEM: {
      readonly MODIFICATION_DEADLINE_HOUR: number;
      readonly SALES_TRANSFER_HOUR: number;
    };
    readonly NOTIFICATION: {
      readonly DAYS: number[];
      readonly HOURS: number[];
      readonly DEFAULT_DAY: number;
      readonly DEFAULT_HOUR: number;
      readonly SCHEDULE_MONTHS_AHEAD: number;
    };
    readonly WEEKEND: {
      readonly SUNDAY: number;
      readonly SATURDAY: number;
    };
  };
}

export {};
